### ISSUE TITLE
Tensorflow 1.0?

### ISSUE THREAD

**Issue by dulex123** [floydhub/dl-docker#40]
Hi,
Thanks for this great image, it is a lot of help!
Is there any reason not to update tensorflow from 0.8 to 1.0?

Thanks,
Dusan

**Comment by saiprashanths** [comment]
I'll update all the libraries to their latest versions this weekend :)

**Comment by dulex123** [comment]
Awesome!

**Comment by gabamnml** [comment]
Never happened...
