### ISSUE TITLE
Tensorflow doesn't work after cuda update for some reason

### ISSUE THREAD

**Issue by nikolajovicic** [floydhub/dl-docker#41]
I try to import tensorflow and it gives me this error:

![image](https://cloud.githubusercontent.com/assets/5502139/22857912/dacdacc2-f0af-11e6-9e63-bfb289827654.png)

Do you have any ideas why it searches for the old CUDA library?

**Comment by nikolajovicic** [comment]
This issue has been fixed by using ubuntu 14.04 image and tensorflow 1.0, I have created a pull request, please close this issue as soon as you have merged it.
#43

**Comment by saiprashanths** [comment]
Thanks for your PR! Tensorflow 1.0 has breaking changes and is not compatible with previous versions, so changing to that is probably not the best yet.

I've been busy with my own startup, so haven't had a chance to rewrite dl-docker to the latest yet. I've, however, separately created several individual docker images for various DL frameworks: https://hub.docker.com/r/floydhub/ (all code is on Github) 

If anyone wants to take take a stab at creating a stable dl-docker before I get to it, please feel free to do so.
